### ISSUE TITLE
putEvents接口第一次调用写入2条数据

### ISSUE THREAD

**Issue by lkmxsxd** [apache/rocketmq-eventbridge#135]
当第一次基于内置DB启动EB时调用putEvents接口会写入2条msgId相同的消息到MQ。
复现方法：
1、如果不是第一次基于内置DB启动需要删除内置DB的数据库文件
2、删除MQ中生成的主题以及消费者（可选）
3、启动
4、调用putEvents接口发送消息
![image](https://github.com/apache/rocketmq-eventbridge/assets/34312552/23cb146e-3835-4bef-99a9-9a438381ffdb)

**Comment by 2011shenlin** [comment]
看上去是同一条消息，是MQ dashboard的展示问题，MsgId一样。如果EB发送两次到MQ，会生成两条消息，MsgId不一样。

经过多次测试，我们这边通过mqadmin工具查看正常：
![image](https://github.com/apache/rocketmq-eventbridge/assets/8605835/50a74420-70cc-4b4c-b188-5fcae38424df)

**Comment by 2011shenlin** [comment]
经确认，实际只有1条数据，是dashboard展示问题。
