### ISSUE TITLE
eventBridge目标源，不支持http

### ISSUE THREAD

**Issue by jiangzhoukim** [apache/rocketmq-eventbridge#155]
![1701249531552](https://github.com/apache/rocketmq-eventbridge/assets/59599549/1bf98df2-406e-464d-aafc-e7a1c717ceda)

**Comment by jiangzhoukim** [comment]
请问是否有关于项目的API文档，以及事件目标源支持的类型描述补充

**Comment by jiangzhoukim** [comment]
![1701249531552](https://github.com/apache/rocketmq-eventbridge/assets/59599549/bc6595a3-8368-47ab-a779-ffd78d658c58)

**Comment by Jashinck** [comment]
支持HTTP目标的，Connector同RocketMQ Connector共建。快速开始文档参考：https://github.com/apache/rocketmq-eventbridge/blob/main/docs/cn/RocketMQEventBridgeQuickStart.md

**Comment by jiangzhoukim** [comment]
请问创建http目标源接口需要传什么参数

**Comment by 2011shenlin** [comment]
参数可以参考rocketmq-connect-http，保持一致：https://github.com/apache/rocketmq-connect/tree/master/connectors/rocketmq-connect-http
