### ISSUE TITLE
执行创建事件总线实例提示“LoginFailed”

### ISSUE THREAD

**Issue by lkmxsxd** [apache/rocketmq-eventbridge#65]
通过官网快速开始教程，创建事件总线提示：`{"requestId":"2e35abd6-b0b8-4781-bbdc-2610480aff3e","code":"LoginFailed","message":"Login failed."}`
执行指令：`curl -X POST --header "Content-Type: application/json" --data { "eventBusName":"demo-bus","description":"a demo bus."} http://localhost:7007/bus/createEventBus`
在部署rocketmq eventbridge 的application.properties配置文件中未提及认证的部分

**Comment by 2011shenlin** [comment]
https://github.com/apache/rocketmq-eventbridge/issues/50
