### ISSUE TITLE
启动eventbridge"management.server.port"未被监听

### ISSUE THREAD

**Issue by lkmxsxd** [apache/rocketmq-eventbridge#66]
启动eventbridge"management.server.port=7008"未被监听，提示如下图，日志中出现了close connect 但是好像不是错误提示。
如图：
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/34312552/228120008-496c412f-2724-4f4a-b242-240f3c61e11a.png">

配置文件：
<img width="1347" alt="image" src="https://user-images.githubusercontent.com/34312552/228120798-c562c5da-01db-43ce-aa05-c1a0324b86bc.png">

**Comment by 2011shenlin** [comment]
curl http://127.0.0.1:7008/health, what result is returned？
