### ISSUE TITLE
Failed during checkstyle execution

### ISSUE THREAD

**Issue by lkmxsxd** [apache/rocketmq-eventbridge#67]
error: Not allow chinese character !

`org.apache.rocketmq.eventbridge.domain.common.exception.EventBridgeErrorCode#RequestParameterInvalid`

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/34312552/228200992-76a15dbf-c734-4b99-8c0b-1619499a069b.png">

**Comment by 2011shenlin** [comment]
@zhaohai666

**Comment by zhaohai666** [comment]
Because of the Chinese exclamation point?

**Comment by lkmxsxd** [comment]
> Because of the Chinese exclamation point?

yes

**Comment by zhaohai666** [comment]
#73
